site:
  tab: "My Blog"
  heroTitle: "Vivid & Easy Math Courses"
  heroDescription: "Vivid & Easy Math Courses description"
  theme:
    light: "winter"
    dark: "dracula"
    code: "github-dark"
user:
  site: "http://localhost:4321"
  email: "test@test.com"
  twitter: "@Timmy_Y0"
  social:
    - name: "twitter"
      href: "https://twitter.com/"
      icon: "lucide:twitter"
    - name: "github"
      href: "https://github.com/"
      icon: "lucide:github"
    - name: "email"
      href: "mailto:test@test.com"
      icon: "lucide:mail"
    - name: "rss"
      href: "/rss.xml"
      icon: "lucide:rss"
