site:
  tab: "My Blog"
  heroTitle: "Vivid & Easy Math Courses"
  heroDescription: "Vivid & Easy Math Courses description"
  theme:
    light: "winter"
    dark: "dracula"
    code: "github-dark"
  aboutme: "I'm a YouTuber with a deep passion for mathematics and science. My goal is to create engaging and intuitive educational content that simplifies complex scientific concepts, making them accessible and easier to understand for everyone."
user:
  site: "http://localhost:4321"
  email: "test@test.com"
  twitter: "@Timmy_Y0"
  social:
    - name: "youtube"
      href: "https://www.youtube.com/"
      icon: "lucide:youtube"
    - name: "twitter"
      href: "https://twitter.com/"
      icon: "lucide:twitter"
    - name: "github"
      href: "https://github.com/"
      icon: "lucide:github"
    - name: "email"
      href: "mailto:test@test.com"
      icon: "lucide:mail"
    - name: "rss"
      href: "/rss.xml"
      icon: "lucide:rss"
